probe-rs/cargo-embed

- Cargo.lock
- Cargo.toml
- README.md
- src/config/mod.rs
Changes:
- Add support for local config files
- Add support for dotted config files (`.embed.toml` and `.embed.local.toml`)
- Make it clear that the non-`.local` config files should be checked in
- Remove support for INI and HJSON files, see commit message for details
Note: Untested!
> Config improvements

- Cargo.lock
- Cargo.toml
- src/config/default.toml
- src/config/mod.rs
- src/rttui/app.rs
- src/rttui/channel.rs
Optional client-side timestamps:
Unfortunately this requires Chrono, because std can't really do stuff like proper date formatting.
Open question: These timestamps are not very precise, they depend on the polling interval and may be delayed by other tasks. Should we remove milliseconds from the dates to avoid "faking precision", or are they still useful?
> RTTUI: Client side timestamps

- Cargo.lock
- src/main.rs
- src/rttui/app.rs
Without this pull request, a panic in `App` looks like this on my machine:
Not only is the formatting messed up, it also basically destroys my terminal (see comment in the code for details) and I have to start a new one.
With this pull request, it looks like this:
Much better, if you ask me.
I don't know yet what causes the panic from those screenshots. I'm still investigating, but this issue was so annoying, that I decided it was time for a deep-dive into Rust's panicking behavior first.
> Prevent panic in `App` from messing up the user's terminal

- src/logging.rs
Previously the `RUST_LOG` env var would always get overridden by the default config and was thus useless.
Now overriding the config seems to work nicely!
> Allow overriding logging config with RUST_LOG

- src/config/mod.rs
Previously, `cargo embed asdf` would panic. Now, an error message is printed, listing available configs.
> Handle unknown configs without panicking

- Cargo.lock
- Cargo.toml
- src/rttui/app.rs
- src/rttui/channel.rs
For #9 
This scrolling issue around paragraph seems related https://github.com/fdehau/tui-rs/issues/89
It put me onto just wrapping before giving text to tui list widget.
Allows to not use paragraph at all, and keep using list.
However.. hard to get access to terminal width, which could change dynamically, inside the rtt polling.
Could instead not do any formatting in channel and do it all in app.rs but then hard to do timestamps. 
Even with something like this we still need some kind of vertical scrolling solution or were still just losing data above now
https://github.com/fdehau/tui-rs/issues/61
Thoughts?
> Text wrapping

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/rttui/channel.rs
This is something I found useful during debugging. It can't be merged before new versions of `probe-rs` and `probe-rs-rtt` are released.
Specifically, this PR depends on the following upstream PRs:
- https://github.com/probe-rs/probe-rs/pull/283
- https://github.com/probe-rs/probe-rs-rtt/pull/6
As of this writing, the latest version of `probe-rs` is 0.7.1, the latest version of `probe-rs-rtt` is 0.2.0. If you're reading this when new versions have been released, and this pull request is still a draft, feel free to ping me.
> Upgrade to latest `probe-rs` / Derive `Debug` for `ChannelState`

- src/main.rs
Here's what the multi-line formatting looks like:
> Small debug message improvement; formatting of multi-line errors

- CHANGELOG.md
- src/config/default.toml
- src/config/mod.rs
- src/main.rs
Allow resetting without flashing.
The 0.8 config should still work, but the `halt_afterwards` flashing config is deprecated. It belongs in the reset section. In 0.10 we can remove it.
Also note that while running, my JLink fails to reset the target (but it works with JLinkExe). That seems to be an unrelated bug (which should now be easier to reproduce).
> Reset without flashing

- Cargo.lock
- Cargo.toml
- src/main.rs
I needed this to make cargo-embed work with stm32h743v, flashing and rtt works 👍 
Not sure what to do about the `[patch]`, maybe wait for a probe-rs release and then adapt/ merge or put the fix into some other commit.
this was changed in https://github.com/probe-rs/probe-rs/pull/322
> make embed events compatible again with ProgressEvent from probe-rs

- src/config/default.toml
- src/config/mod.rs
- src/main.rs
- src/rttui/app.rs
- src/rttui/channel.rs
- src/rttui/mod.rs
> first pass at saving history out to file on exit

- Cargo.lock
- Cargo.toml
- src/main.rs
as discussed on matrix this may be helpful for user bug reports
I could not find a way to format the string at compile time in which
case I could have used something like:
`#[structopt(version = git_version::git_version!() + .... )]`
output:
```
$ cargo run - --version
cargo-embed 0.9.1
git commit: baca8ba
```
If you want to do the cargo update stuff separately I can also adjust after thats done.
Tested on macos only.
> add git commit hash to version

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/config/default.toml
- src/main.rs
- src/rttui/app.rs
- src/rttui/channel.rs
Updated to incorporate latest upstream of defmt and cargo-embed changes (https://github.com/probe-rs/cargo-embed/pull/73)
```
0.000000 INFO Hello, world!
└─ src/main.rs:43
0.000001 INFO rcc
└─ src/main.rs:49
^C⏎
```
> defmt integration

- src/rttui/app.rs
Flush the log file when exiting, otherwise it could happen that not everything is written to the file.
> Flush log on exit

- Cargo.lock
- Cargo.toml
- src/config/mod.rs
- src/main.rs
The `config` crate has some limitations which make it undesirable.
`figment` has improved error reporting, and allows the user to be
alerted if they define invalid (i.e. unknown) configuration items.
> Switch to the figment crate for configuration parsing.

- src/rttui/app.rs
When `DisableMouseCapture` is executed, this leads to a panic! on Windows because `EnableMouseCapture` is never called.
The `clean_up_terminal()` function is called in the panic handler, so this leads to a panic inside a panic, as described in #241.
This PR should fix #241.
> Do not call DisableMouseCapture, EnableMouseCapture is never called

- src/config/default.toml
Since #159 it has been possible to use RTT and GDB at the same time.
> Remove mutual exclusion comment on RTT / GDB

- src/rttui/app.rs
I wasn't getting any data when using `defmt-0.3.0`. After checking up, I was getting data encoded with Rzcobs.
This commit replaces the custom stream decoding with `defmt-decoder` helpers similarly as probe-run does.
> Update Defmt decoder to handle Rzcobs encoding

- README.md
I ran into a couple snags installing on Debian. It seems like these notes might be useful on https://probe.rs/docs/tools/cargo-embed/ too? I don't see anything about the prerequisites/dependencies there.
> Add note in README about old libusb versions

- README.md
I wrote some basic docs based on playing around with the rtt ui and skimming the source code, and thought they might be helpful.
> Add basic docs for RTT UI

- src/rttui/app.rs
In my app I log messages via defmt and also dump raw data over other rtt channels. I want to save logs of the string and binary channels, but I don't care that the defmt channel isn't logged.
cargo-embed currently saves up to the first defmt tab, and then panic with "You encountered a bug. Please open an issue on Github.".
With this PR cargo-embed saves all non-defmt (string or binary) tabs, and warns for every defmt tab it skips.
> Warn on unsavable tabs instead of panicking

- src/main.rs
Following on from chat - this is just meant to put the GDB stub information on the terminal when running without more verbose logging enabled.
> Raise logging level of gdb_connection_string

- README.md
Fixes https://github.com/probe-rs/cargo-embed/issues/325. I have encountered the same error while trying to install `cargo-embed` on a WSL installation of Ubuntu.
> Add missing dependency `libudev-dev` to README list.

- src/main.rs
Clap overrides version handling by default, but we didn't pass any version to clap, so it's empty. Instead, disable version handling in clap and handle it ourselves.
Fixes #389.
> CLI: Fix missing version in -V/--version output
