probe-rs/cargo-embed

Cargo.lock, Cargo.toml, src/main.rs
Signed-off-by: Daniel Egger <daniel@eggers-club.de>
=> Use anyhow instead of failure for more ergnomic errors

Cargo.lock, src/main.rs, src/rttui/app.rs
This is what I'm seeing without this PR:
This is what I'm seeing with it:
And here's what I'm seeing with this PR in combination with https://github.com/probe-rs/probe-rs-rtt/pull/8:
=> Fix panic in RTT UI, if no channels were configured

src/main.rs
=> Improve warnings

src/config/mod.rs
This patch make it work for now and should not break even if the bug in the config-crate is fixed.
=> Workaround for #30, to ensure local config files are loaded

.github/bors.toml, .github/dependabot.yml, .github/workflows/ci.yml
Same as in the other repositories, use `bors r+` to merge after approving.
=> Add bors and dependabot

.github/workflows/ci.yml
Version libftdi1-dev is required, not libftdi-dev 🤦‍♂️
=> Use proper libftdi version

Cargo.lock, Cargo.toml, src/rttui/app.rs
did very basic rtt smoke test, please someone else run this as well :D
=> update to tui 0.10.0

src/main.rs
same PR notes as for --probe just less lines ;)
=> add --chip

src/main.rs
mostly copied form cargo-flash, cli arg takes precedence over config 
I gathered we wanted to support this and the goal was to unify flash and embed args?
=> add --probe like present in cargo-flash

src/main.rs
This fixes a bug where the main thread would not wait on the GDB thread if RTT was disabled. Thus one would not be able to run GDB without RTT.
=> Fix a bug with GDB now on a second thread.

Cargo.lock, Cargo.toml, src/config/default.toml, src/config/mod.rs, src/main.rs
=> Adapt to the flash api changes

CHANGELOG.md
=> Add changelog entry for PR 205

src/rttui/app.rs, src/rttui/event.rs
If the access to the probe takes a long time, input events are not
processed properly anymore. It seems that the tick events occur
too often in that case, and the actual input is not processed anymore.
By using recv_timeout, we do not need the Tick events, which seems
to solve this issue.
=> Improve input event handling (fix #207)

Cargo.lock, src/main.rs
I needed this patch to be able to build.
=> Add in field that has been added to probe-rs

src/main.rs
=> Stop using rf3339 in log filenames

src/main.rs
If defmt output is enabled in the `cargo embed` config, but the binary
being debugged doesn't use defmt, then `cargo embed` panic()ed on unwrap
without printing any useful error message to the user.  Log this at
error level instead.
=> Log error instead of panicking when defmt erroneously enabled.

Cargo.lock, src/main.rs
I only have a shallow understanding of permissions in this context, but this at least compiles and seems to work for my usage.
=> Update probe-rs `attach` calls to add permissions

CHANGELOG.md, Cargo.lock, src/config/default.toml, src/config/mod.rs, src/main.rs, src/rttui/channel.rs
Here's a first stab at https://github.com/probe-rs/cargo-embed/issues/258
=> Add ability to configure RTT channel blocking mode

CHANGELOG.md, Cargo.lock, src/main.rs
* Update GDB calls
* Update for u64 address space changes
Signed-off-by: Ryan Fairfax <ryan@thefaxman.net>
=> Updates for latest probe-rs release

Cargo.lock, Cargo.toml, src/rttui/app.rs
=> Fix logging on Windows

README.md, src/rttui/app.rs, src/rttui/channel.rs
This adds a clear tab shortcut (CTRL + l).
=> Add clear tab keyboard shortcut
